services:
  backend:
    build: .
    volumes:
      - .:/app/django-crm
    depends_on:
      - db
    env_file: .env
    ports:
      - '8000:5000'

  db:
    image: postgres:16-alpine3.19
    env_file: .env
    volumes:
      - postgres_data:/app/django-crm/postgres/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres_data:

  