services:
  backend:
    build: .
    volumes:
      - .:/app/django-crm
    depends_on:
      - db
    env_file: .env
    ports:
      - '8080:5000'

  db:
    image: postgres:16-alpine3.19
    env_file: .env
    ports:
      - '5432:5432'

  