name: Securely copy file to server
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  confirm_secrets:
    name: Confirm Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Print the secrets
        run: |
          echo "Host: ${{ secrets.AWS_HOST }}"
          echo "User: ${{ secrets.AWS_USER }}"
          echo "Key: ${{ secrets.AWS_KEY }}"

  ssh_inside:
    name: SSH into the server
    needs: confirm_secrets
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2
        run: |
          ssh -i ${{ secrets.AWS_KEY }} ${{ secrets.AWS_USER}}@${{ secrets.AWS_HOST}} "mkdir ndani"
