name: Securely copy file to server
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  confirm_secrets:
    name: Confirm Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Print the secrets
        run: |
          echo "Host: ${{ secrets.AWS_HOST }}"
          echo "User: ${{ secrets.AWS_USER }}"
          echo "Key: ${{ secrets.AWS_KEY }}"

  ssh_inside:
    name: SSH into the server
    needs: confirm_secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a file to store the private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/aws_key
          chmod 400 ~/.ssh/aws_key

      - name: Securely copy file to the server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/aws_key entrypoint.sh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:~

      - name: SSH into EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key ${{ secrets.AWS_USER}}@${{ secrets.AWS_HOST}} "mkdir ndani"
