# My first github action (creating random workflows)
name: My first Github Action workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  my_first_job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          FIRST_NAME: Ronny
          LAST_NAME: Mokaya
        run: |
          echo "Hello $FIRST_NAME $LAST_NAME"

  second_job:
    name: Second Job
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
      - name: Print a done statement
        run: |
          echo "Done with running both jobs"

  third_job:
    name: Third Job
    runs-on: ubuntu-latest
    needs: second_job
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v6.7.0